AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Gateway with Rate Limiting and Lambda Backend'

Resources:
  ApiBackendFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiGatewayRateLimitingLambda
      Handler: index.handler
      Role: arn:aws:iam::641002720432:role/ec2-role
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log('Event received:', JSON.stringify(event));
            
            return {
              statusCode: 200,
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                message: 'Hello from Lambda!',
                timestamp: new Date().toISOString(),
                requestId: event.requestContext?.requestId || 'unknown',
              }),
            };
          };
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 128

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RateLimitedAPI
      Description: API Gateway with rate limiting enabled

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: test

  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiBackendFunction.Arn}/invocations

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiBackendFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/test

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiMethod
    Properties:
      RestApiId: !Ref ApiGateway
      Description: API Gateway deployment

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiDeployment
      RestApiId: !Ref ApiGateway
      StageName: prod
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          ThrottlingRateLimit: 100
          ThrottlingBurstLimit: 200

Outputs:
  ApiEndpoint:
    Description: URL of the API Gateway endpoint
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/test
